make backup only if mysql server is running

diff --git a/update_mariadb b/update_mariadb
--- a/update_mariadb
+++ b/update_mariadb
@@ -9,21 +9,27 @@ fi
 
 . /usr/local/src/update/lib/functions
 
-cd /usr/local/src/mariadb
+# make a backup of mysql databases
+function make_backup () {
+	echo -en "Will make a backup of you database\nEnter your root mysql password: "
+	read pw
+	mysqldump -u root --password=$pw --all-databases > /var/tmp/mysql-backup-$(date +'%Y-%m-%d-%H-%M').sql
+	if [ $? -eq 1 ]; then
+		echo "ERROR mysqldump failed..."
+		exit 1
+	fi
+}
+
+mkdir -p /usr/local/src/mariadb/ && cd /usr/local/src/mariadb
 clean_oldsrc mariadb-$mariadb_version
 download_src "https://downloads.mariadb.org/f/mariadb-$mariadb_version/kvm-tarbake-jaunty-x86/mariadb-$mariadb_version.tar.gz/from/http:/mirror3.layerjet.com/mariadb" mariadb-$mariadb_version.tar.gz
 
 extract_and_compile mariadb $mariadb_version "--prefix=/usr/local/mariadb/$mariadb_version --with-mysqld-user=mysql --with-mysqlmanager --enable-profiling --with-plugins=myisam,archive,blackhole,csv,ibmdb2i,innodb_plugin,aria,myisammrg,xtradb,federated,partition,pbxt"
 
-# make a backup of mysql databases
-echo -en "Will make a backup of you database\nEnter your root mysql password: "
-read pw
-mysqldump -u root --password=$pw --all-databases > /var/tmp/mysql-backup-$(date +'%Y-%m-%d-%H-%M').sql
-if [ $? -eq 1 ]; then
-	echo "ERROR mysqldump failed..."
-	exit 1
+pgrep mysql > /dev/null 2>&1
+if [ $? == 0 ]; then
+	make_backup
 fi
-
 
 # relink
 /etc/init.d/mysql stop
