use config file for path

diff --git a/update_apache2 b/update_apache2
--- a/update_apache2
+++ b/update_apache2
@@ -11,22 +11,27 @@ if [ "x$apache_version" == "x" -o "x$php_version" == "x" -o "x$mod_sec_version" 
 	exit 1
 fi
 
+. $(dirname $0)/config.sh
+. $(dirname $0)/lib/functions
+
+init
+
 # clean up all old directories
-rm -rf /usr/local/src/httpd-$apache_version?(.tar.gz)
-rm -rf /usr/local/src/php-$php_version?(.tar.bz2)
-rm -rf /usr/local/src/subversion-$svn_version?(.tar.gz)
-rm -rf /usr/local/src/modsecurity-apache-$mod_sec_version?(.tar.gz)
+rm -rf $spath/httpd-$apache_version?(.tar.gz)
+rm -rf $spath/php-$php_version?(.tar.bz2)
+rm -rf $spath/subversion-$svn_version?(.tar.gz)
+rm -rf $spath/modsecurity-apache-$mod_sec_version?(.tar.gz)
 
 # compile apache
-mkdir -p /usr/local/src && cd /usr/local/src
-wget http://mirror.serversupportforum.de/apache//httpd/httpd-$apache_version.tar.gz -O /usr/local/src/httpd-$apache_version.tar.gz
+cd $spath
+wget http://mirror.serversupportforum.de/apache//httpd/httpd-$apache_version.tar.gz -O $spath/httpd-$apache_version.tar.gz
 if [ $? -ge 1 ]; then
   echo "Couldn't download httpd-$apache_version.tar.gz"
   exit 1
 fi
 tar -xzvf httpd-$apache_version.tar.gz
-cd /usr/local/src/httpd-$apache_version
-CPPFLAGS="-DOPENSSL_NO_SSL2" ./configure --prefix=/usr/local/apache2/$apache_version --enable-mods-shared="headers authz_svn auth_basic authn_file alias dav_lock dav_fs dav dav_svn cache disk_cache mem_cache ssl cgi rewrite unique_id" --enable-auth-digest --enable-substitute --enable-info --enable-vhost-alias --enable-status --enable-autoindex --enable-log-forensic --with-unique-id --enable-so --enable-deflate --enable-dav --enable-unixd --with-ssl=/usr/local/openssl/current
+cd $spath/httpd-$apache_version
+CPPFLAGS="-DOPENSSL_NO_SSL2" ./configure --prefix=$ipath/apache2/$apache_version --enable-mods-shared="headers authz_svn auth_basic authn_file alias dav_lock dav_fs dav dav_svn cache disk_cache mem_cache ssl cgi rewrite unique_id" --enable-auth-digest --enable-substitute --enable-info --enable-vhost-alias --enable-status --enable-autoindex --enable-log-forensic --with-unique-id --enable-so --enable-deflate --enable-dav --enable-unixd --with-ssl=$ipath/openssl/current
 if [ $? -eq 1 ]; then
 	echo "configure apache2 failed..."
 	exit 1
@@ -41,22 +46,22 @@ if [ $? -eq 1 ]; then
 	echo "ERROR make install apache failed..."
 	exit 1
 fi
-ln -s /usr/local/apache2/$apache_version /usr/local/apache2/current
+ln -s $ipath/apache2/$apache_version $ipath/apache2/current
 
 # compile php5
-cd /usr/local/src
-wget http://de2.php.net/get/php-$php_version.tar.bz2/from/de1.php.net/mirror -O /usr/local/src/php-$php_version.tar.bz2
+cd $spath
+wget http://de2.php.net/get/php-$php_version.tar.bz2/from/de1.php.net/mirror -O $spath/php-$php_version.tar.bz2
 if [ $? -ge 1 ]; then
   echo "Couldn't download php-$php_version.tar.bz2"
   exit 1
 fi
-tar -xjvf /usr/local/src/php-$php_version.tar.bz2
-cd /usr/local/src/php-$php_version
+tar -xjvf $spath/php-$php_version.tar.bz2
+cd $spath/php-$php_version
 #vim -c '%s/^\(\s*test.*recode_conflict.*\)/#\1/g' -c 'wq!' configure
 sed -i 's/^\(\s*test.*recode_conflict.*\)/#\1/g' configure
 sed -i 's/^\(\s*test.*recode_conflict.*\)/dnl \1/g' ext/recode/config9.m4
      
-./configure  --prefix=/usr/local/php5/$php_version --with-pear --enable-cli --with-mysql --with-mysql-sock --enable-calendar --with-pcre-regex --with-mysqli --with-mcrypt --with-recode --with-gd --with-zlib --with-imap --with-imap-ssl --with-kerberos --enable-bcmath --with-pdo-mysql --with-apxs2=/usr/local/apache2/$apache_version/bin/apxs --with-freetype-dir --enable-gd-native-ttf --with-gettext --enable-dom --enable-sockets --enable-mbstring --with-jpeg-dir=/usr/lib --with-png-dir --enable-zip --with-curl --enable-json --enable-exif --with-libxml-dir=/usr/local/libxml2
+./configure  --prefix=$ipath/php5/$php_version --with-pear --enable-cli --with-mysql --with-mysql-sock --enable-calendar --with-pcre-regex --with-mysqli --with-mcrypt --with-recode --with-gd --with-zlib --with-imap --with-imap-ssl --with-kerberos --enable-bcmath --with-pdo-mysql --with-apxs2=$ipath/apache2/$apache_version/bin/apxs --with-freetype-dir --enable-gd-native-ttf --with-gettext --enable-dom --enable-sockets --enable-mbstring --with-jpeg-dir=/usr/lib --with-png-dir --enable-zip --with-curl --enable-json --enable-exif --with-libxml-dir=/usr/local/libxml2
 if [ $? -eq 1 ]; then
 	echo "configure php failed..."
 	exit 1
@@ -71,18 +76,18 @@ if [ $? -eq 1 ]; then
 	echo "ERROR make install php failed..."
 	exit 1
 fi
-ln -s /usr/local/php5/$php_version /usr/local/php5/current
+ln -s $ipath/php5/$php_version $ipath/php5/current
 
 # compile subversion for mod_dav_svn
-cd /usr/local/src
-wget http://apache.mirror.digionline.de/subversion/subversion-$svn_version.tar.gz -O /usr/local/src/subversion-$svn_version.tar.gz
+cd $spath
+wget http://apache.mirror.digionline.de/subversion/subversion-$svn_version.tar.gz -O $spath/subversion-$svn_version.tar.gz
 if [ $? -ge 1 ]; then
   echo "Couldn't download subversion-$svn_version.tar.gz"
   exit 1
 fi
-tar -xzvf /usr/local/src/subversion-$svn_version.tar.gz
-cd /usr/local/src/subversion-$svn_version
-./configure --with-apxs=/usr/local/apache2/$apache_version/bin/apxs
+tar -xzvf $spath/subversion-$svn_version.tar.gz
+cd $spath/subversion-$svn_version
+./configure --with-apxs=$ipath/apache2/$apache_version/bin/apxs
 if [ $? -eq 1 ]; then
 	echo "configure subversion failed..."
 	exit 1
@@ -99,15 +104,15 @@ if [ $? -eq 1 ]; then
 fi
 
 # compile mod_security
-cd /usr/local/src
-wget https://www.modsecurity.org/tarball/$mod_sec_version/modsecurity-apache_$mod_sec_version.tar.gz -O /usr/local/src/modsecurity-apache_$mod_sec_version.tar.gz
+cd $spath
+wget https://www.modsecurity.org/tarball/$mod_sec_version/modsecurity-apache_$mod_sec_version.tar.gz -O $spath/modsecurity-apache_$mod_sec_version.tar.gz
 if [ $? -ge 1 ]; then
-  echo "Couldn't download /modsecurity-apache_$mod_sec_version.tar.gz"
+  echo "Couldn't download modsecurity-apache_$mod_sec_version.tar.gz"
   exit 1
 fi
-tar -xzvf /usr/local/src/modsecurity-apache_$mod_sec_version.tar.gz 
-cd /usr/local/src/modsecurity-apache_$mod_sec_version
-./configure --with-apxs=/usr/local/apache2/$apache_version/bin/apxs
+tar -xzvf $spath/modsecurity-apache_$mod_sec_version.tar.gz 
+cd $spath/modsecurity-apache_$mod_sec_version
+./configure --with-apxs=$ipath/apache2/$apache_version/bin/apxs
 if [ $? -eq 1 ]; then
 	echo "configure modsecurity failed..."
 	exit 1
@@ -124,32 +129,32 @@ if [ $? -eq 1 ]; then
 fi
 
 # copy modules
-cp /usr/local/src/subversion-$svn_version/subversion/mod_dav_svn/.libs/mod_dav_svn.so /usr/local/apache2/$apache_version/modules/
-cp /usr/local/src/subversion-$svn_version/subversion/mod_authz_svn/.libs/mod_authz_svn.so /usr/local/apache2/$apache_version/modules/
+cp $spath/subversion-$svn_version/subversion/mod_dav_svn/.libs/mod_dav_svn.so $ipath/apache2/$apache_version/modules/
+cp $spath/subversion-$svn_version/subversion/mod_authz_svn/.libs/mod_authz_svn.so $ipath/apache2/$apache_version/modules/
 
 # relink everything
-cd /usr/local/apache2/$apache_version
+cd $ipath/apache2/$apache_version
 mv conf conf.orig
 ln -s /etc/apache2 ./conf
 
-cd /usr/local/apache2
+cd $ipath/apache2
 rm -f current
 ln -s ./$apache_version current
 
-if [ ! -f /usr/local/apache2/$apache_version/modules/mod_security2.so ]; then
+if [ ! -f $ipath/apache2/$apache_version/modules/mod_security2.so ]; then
 	echo "NO mod_security.so installed"
 fi
-if [ ! -f /usr/local/apache2/$apache_version/modules/libphp5.so ]; then
+if [ ! -f $ipath/apache2/$apache_version/modules/libphp5.so ]; then
 	echo "NO libphp5.so installed"
 fi
-if [ ! -f /usr/local/apache2/$apache_version/modules/mod_dav_svn.so ]; then
+if [ ! -f $ipath/apache2/$apache_version/modules/mod_dav_svn.so ]; then
 	echo "NO mod_dav_svn.so installed"
 fi
-if [ ! -f /usr/local/apache2/$apache_version/modules/mod_authz_svn.so ]; then
+if [ ! -f $ipath/apache2/$apache_version/modules/mod_authz_svn.so ]; then
 	echo "NO mod_authz_svn.so installed"
 fi
 
-#apachectl -t
-#if [ $? -eq 0 ]; then
-#	echo "You will need to restart apache now"
-#fi
+apachectl -t
+if [ $? -eq 0 ]; then
+	echo "You will need to restart apache now"
+fi
