git don't like links

diff --git a/update_mariadb b/update_mariadb
--- a/update_mariadb
+++ b/update_mariadb
@@ -1,1 +1,45 @@
-/opt/scripts/bash/trunk/update_opensource/update_mariadb
+#!/bin/bash
+
+mariadb_version=$1
+
+if [ "x$mariadb_version" == "x" ]; then
+	echo "Usage: $0 <mariadb version>"
+	exit 1
+fi
+
+if [ ! -f /usr/local/src/mariadb/mariadb-$mariadb_version.tar.gz ]; then
+	echo "Source mariadb-$mariadb_version.tar.gz does not exist."
+	exit 1
+fi
+
+cd /usr/local/src/mariadb && tar -xvzf mariadb-$mariadb_version.tar.gz
+cd mariadb-$mariadb_version
+./configure --prefix=/usr/local/mariadb/$mariadb_version --with-mysqld-user=mysql --with-mysqlmanager --enable-profiling --with-plugins=myisam,archive,blackhole,csv,ibmdb2i,innodb_plugin,aria,myisammrg,xtradb,federated,partition,pbxt
+make
+if [ $? -eq 1 ]; then
+	echo "ERROR make failed..."
+	exit 1
+fi
+make install
+if [ $? -eq 1 ]; then
+	echo "ERROR make install failed..."
+	exit 1
+fi
+
+# make a backup of mysql databases
+echo -en "Will make a backup of you database\nEnter your root mysql password: "
+read pw
+mysqldump -u root --password=$pw --all-databases > /var/tmp/mysql-backup-$(date +'%Y-%m-%d-%H-%M').sql
+if [ $? -eq 1 ]; then
+	echo "ERROR mysqldump failed..."
+	exit 1
+fi
+
+
+# relink
+/etc/init.d/mysql stop
+rm /usr/local/mariadb/current && ln -s /usr/local/mariadb/$mariadb_version /usr/local/mariadb/current
+/etc/init.d/mysql start
+
+echo -e "Your backup is /var/tmp/mysql-backup-$(date +'%Y-%m-%d-%H-%M').sql\n"
+
diff --git a/update_php5 b/update_php5
--- a/update_php5
+++ b/update_php5
@@ -1,1 +1,76 @@
-/opt/scripts/bash/trunk/update_opensource/update_php5
+#!/bin/bash
+
+php_version=$1
+apache_version=$2
+mode=$3
+
+if [ "x$php_version" == "x" -o "x$apache_version" == "x" ]; then
+	echo "Usage: $0 <php version> <apache version> <update|rollback>"
+	exit 1
+fi
+
+function update() {
+    cd /usr/local/src
+    wget http://de2.php.net/get/php-$php_version.tar.bz2/from/de1.php.net/mirror -O php-$php_version.tar.bz2
+    tar -xjvf /usr/local/src/php-$php_version.tar.bz2
+    # compile php5
+    cd /usr/local/src/php-$php_version
+    # patch php5 to work with recode and imap
+    vim -c '%s/^\(.*test.*recode_conflict.*\)/#\1/gc' -c 'wq!' configure
+    vim -c '%s/^\(.*test.*recode_conflict.*\)/dnl \1/gc' -c 'wq!' ext/recode/config9.m4
+     
+    ./configure  --prefix=/usr/local/php5/$php_version --with-pear --enable-cli --with-mysql --with-mysql-sock --enable-calendar --with-pcre-regex --with-mysqli --with-mcrypt --with-recode --with-gd --with-zlib --with-imap --with-imap-ssl --with-kerberos --enable-bcmath --with-pdo-mysql --with-apxs2=/usr/local/apache2/$apache_version/bin/apxs --with-freetype-dir --enable-gd-native-ttf --with-gettext --enable-dom --enable-sockets --enable-mbstring --with-jpeg-dir=/usr/lib --with-png-dir --enable-zip --with-curl --enable-json --enable-exif --with-libxml-dir=/usr/local/libxml2
+    make
+    if [ $? -eq 1 ]; then
+    	echo "ERROR make failed..."
+    	exit 1
+    fi
+    make install
+    if [ $? -eq 1 ]; then
+    	echo "ERROR make failed..."
+    	exit 1
+    fi
+
+    # after install delete php module line from httpd.conf
+    sed -i '/^LoadModule php5_module/d' /etc/apache2/httpd.conf
+    
+    # relink everything
+    cp libs/libphp5.so /usr/local/php5/$php_version/lib
+    cd /usr/local/php5/$php_version/lib
+    ln -s /etc/php5/apache2/php.ini ./
+    cd /usr/local/php5
+    rm -f current && ln -s ./$php_version ./current
+    
+    rm -f /usr/local/apache2/$apache_version/modules/libphp5.so
+    ln -s /usr/local/php5/current/lib/libphp5.so /usr/local/apache2/$apache_version/modules/libphp5.so
+    
+    if [ ! -f /usr/local/php5/current/lib/php.ini ]; then
+    	echo "NO php.ini linked to current"
+    fi
+    apachectl -t
+    if [ $? -eq 0 ]; then
+    	/etc/init.d/apache2 stop
+    	sleep 4
+    	/etc/init.d/apache2 start
+    fi
+    # needed for sms sending
+    /usr/local/bin/pear install Log
+}
+
+function rollback() {
+    cd /usr/local/php5
+    rm -f current && ln -s ./$php_version ./current
+    apachectl -t
+    if [ $? -eq 0 ]; then
+    	/etc/init.d/apache2 stop
+    	sleep 2
+    	/etc/init.d/apache2 start
+    fi
+}
+
+
+case "$3" in
+    update) update;;
+    rollback) rollback;;
+    *) echo "usage: $0 <php version> <apache version> <update|rollback>";;
+esac
diff --git a/update_zabbix b/update_zabbix
--- a/update_zabbix
+++ b/update_zabbix
@@ -1,1 +1,57 @@
-/opt/scripts/bash/trunk/update_opensource/update_zabbix
+#!/bin/bash
+
+# default configure
+# ./configure --prefix=/usr/local/zabbix/2.0.1 --enable-agent --enable-server --with-libcurl --with-net-snmp --with-ssh2 --with-mysql --enable-proxy --enable-java
+version=$1
+
+
+if [ "x$version" = "x" ]; then
+	echo "Usage: $0 <version>"
+	exit 1
+fi
+
+destdir=/usr/local/zabbix/$version
+builddir=/usr/local/src/zabbix
+
+wget --prefer-family=ipv4 http://downloads.sourceforge.net/project/zabbix/ZABBIX%20Latest%20Stable/$version/zabbix-$version.tar.gz -O /usr/local/src/zabbix/zabbix-$version.tar.gz
+if [ ! -f $builddir/zabbix-$version.tar.gz ]; then
+	echo "Source file zabbix-$version.tar.gz doesn't exist"
+	exit 1
+fi
+
+cd $builddir
+tar -xzvf zabbix-$version.tar.gz
+cd zabbix-$version
+export PATH=$PATH:/usr/local/java/current/bin/
+./configure --prefix=$destdir --enable-agent --enable-server --with-libcurl --with-net-snmp --with-ssh2 --with-mysql --enable-proxy --enable-java --with-unixodbc
+make
+if [ $? -eq 1 ]; then
+	echo "ERROR make failed..."
+	exit 1
+fi
+make install
+if [ $? -eq 1 ]; then
+	echo "ERROR make install failed..."
+	exit 1
+fi
+
+# copy frontend
+cp -R frontends/php $destdir/frontends
+rm -f $destdir/etc/zabbix_agentd.conf $destdir/etc/zabbix_server.conf
+ln -s /etc/zabbix/zabbix_agentd.conf $destdir/etc/
+ln -s /etc/zabbix/zabbix_server.conf $destdir/etc/
+
+# restart zabbix
+/etc/init.d/zabbix-server stop
+/etc/init.d/zabbix-agent stop
+sleep 3
+rm -f /usr/local/zabbix/current && ln -s $destdir /usr/local/zabbix/current
+/etc/init.d/zabbix-server start
+sleep 3
+/etc/init.d/zabbix-agent start
+
+# change ownership of frontend
+chown -R www-data: /usr/local/zabbix/current/frontends
+
+# clean up
+rm -rf /usr/local/src/zabbix/zabbix-$version
