if source couldn't be downloaded exit build script

diff --git a/update_apache2 b/update_apache2
--- a/update_apache2
+++ b/update_apache2
@@ -13,7 +13,7 @@ fi
 
 # clean up all old directories
 rm -rf /usr/local/src/httpd-$apache_version?(.tar.gz)
-rm -rf /usr/local/src/php-$php_version?(.tar.gz)
+rm -rf /usr/local/src/php-$php_version?(.tar.bz2)
 rm -rf /usr/local/src/subversion-$svn_version?(.tar.gz)
 rm -rf /usr/local/src/modsecurity-apache-$mod_sec_version?(.tar.gz)
 
@@ -40,6 +40,10 @@ fi
 
 # compile php5
 wget http://de2.php.net/get/php-$php_version.tar.bz2/from/de1.php.net/mirror -O php-$php_version.tar.bz2
+if [ $? -ge 1 ]; then
+  echo "Couldn't download php-$php_version.tar.bz2"
+  exit 1
+fi
 tar -xjvf /usr/local/src/php-$php_version.tar.bz2
 cd /usr/local/src/php-$php_version
 vim -c '%s/^\(.*test.*recode_conflict.*\)/#\1/gc' -c 'wq!' configure
@@ -59,7 +63,11 @@ fi
 
 # compile subversion for mod_dav_svn
 wget http://apache.mirror.digionline.de/subversion/subversion-$svn_version.tar.gz
-tar -xzvf /usr/local/subversion-$svn_version.tar.gz
+if [ $? -ge 1 ]; then
+  echo "Couldn't download subversion-$svn_version.tar.gz"
+  exit 1
+fi
+tar -xzvf /usr/local/src/subversion-$svn_version.tar.gz
 cd /usr/local/src/subversion-$svn_version
 ./configure --with-apxs=/usr/local/apache2/$apache_version/bin/apxs
 make
@@ -75,6 +83,10 @@ fi
 
 # compile mod_security
 wget https://www.modsecurity.org/tarball/$mod_sec_version/modsecurity-apache_$mod_sec_version.tar.gz
+if [ $? -ge 1 ]; then
+  echo "Couldn't download /modsecurity-apache_$mod_sec_version.tar.gz"
+  exit 1
+fi
 tar -xzvf /usr/local/src/modsecurity-apache_$mod_sec_version.tar.gz 
 cd /usr/local/src/modsecurity-apache_$mod_sec_version
 ./configure --with-apxs=/usr/local/apache2/$apache_version/bin/apxs
@@ -89,7 +101,7 @@ if [ $? -eq 1 ]; then
 	exit 1
 fi
 
-# copy modules
+ copy modules
 cp /usr/local/src/subversion-$svn_version/subversion/mod_dav_svn/.libs/mod_dav_svn.so /usr/local/apache2/$apache_version/modules/
 cp /usr/local/src/subversion-$svn_version/subversion/mod_authz_svn/.libs/mod_authz_svn.so /usr/local/apache2/$apache_version/modules/
 
