stop script if sources can't be download

diff --git a/update_dovecot b/update_dovecot
--- a/update_dovecot
+++ b/update_dovecot
@@ -10,6 +10,10 @@ fi
 
 cd /usr/local/src/dovecot
 wget http://dovecot.org/releases/2.2/dovecot-$dovecot_version.tar.gz
+if [ $? -ge 1 ]; then
+  echo "Couldn't download dovecot-$dovecot_version.tar.gz"
+  exit 1
+fi
 # compile dovecot
 tar -xzvf dovecot-$dovecot_version.tar.gz
 cd dovecot-$dovecot_version
@@ -30,6 +34,10 @@ cd /usr/local/src/dovecot
 # clean up the source directory
 rm -rf dovecot-.*pigeonhole.*
 wget http://www.rename-it.nl/dovecot/2.2/dovecot-2.2-pigeonhole-$pig_version.tar.gz
+if [ $? -ge 1 ]; then
+  echo "Couldn't download dovecot-2.2-pigeonhole-$pig_version.tar.gz"
+  exit 1
+fi
 tar -xzvf dovecot-2.2-pigeonhole-$pig_version.tar.gz
 cd dovecot-2.2-pigeonhole-$pig_version
 ./configure --with-dovecot=/usr/local/dovecot/$dovecot_version/lib/dovecot
diff --git a/update_mariadb b/update_mariadb
--- a/update_mariadb
+++ b/update_mariadb
@@ -12,7 +12,13 @@ if [ ! -f /usr/local/src/mariadb/mariadb-$mariadb_version.tar.gz ]; then
 	exit 1
 fi
 
-cd /usr/local/src/mariadb && tar -xvzf mariadb-$mariadb_version.tar.gz
+cd /usr/local/src/mariadb
+wget https://downloads.mariadb.org/f/mariadb-$mariadb_version/kvm-tarbake-jaunty-x86/mariadb-$mariadb_version.tar.gz/from/http:/mirror3.layerjet.com/mariadb -O mariadb-$mariadb_version.tar.gz
+if [ $? -ge 1 ]; then
+  echo "Couldn't download mariadb-$mariadb_version.tar.gz"
+  exit 1
+fi
+tar -xvzf mariadb-$mariadb_version.tar.gz
 cd mariadb-$mariadb_version
 ./configure --prefix=/usr/local/mariadb/$mariadb_version --with-mysqld-user=mysql --with-mysqlmanager --enable-profiling --with-plugins=myisam,archive,blackhole,csv,ibmdb2i,innodb_plugin,aria,myisammrg,xtradb,federated,partition,pbxt
 make
diff --git a/update_php5 b/update_php5
--- a/update_php5
+++ b/update_php5
@@ -12,6 +12,10 @@ fi
 function update() {
     cd /usr/local/src
     wget http://de2.php.net/get/php-$php_version.tar.bz2/from/de1.php.net/mirror -O php-$php_version.tar.bz2
+    if [ $? -ge 1 ]; then
+      echo "Couldn't download php-$php_version.tar.bz2"
+      exit 1
+    fi
     tar -xjvf /usr/local/src/php-$php_version.tar.bz2
     # compile php5
     cd /usr/local/src/php-$php_version
