download the source

diff --git a/bash/trunk/update_opensource/update_dovecot b/bash/trunk/update_opensource/update_dovecot
--- a/bash/trunk/update_opensource/update_dovecot
+++ b/bash/trunk/update_opensource/update_dovecot
@@ -8,24 +8,26 @@ if [ "x$dovecot_version" == "x" -o "x$pig_version" == "x" ]; then
 	exit 1
 fi
 
-#cd /usr/local/src/dovecot
-## compile dovecot
-#tar -xzvf dovecot-$dovecot_version.tar.gz
-#cd dovecot-$dovecot_version
-#./configure --prefix=/usr/local/dovecot/$dovecot_version --with-shadow --with-pam --with-ssl=openssl --sysconfdir=/etc
-#make
-#if [ $? -eq 1 ]; then
-#	echo "ERROR make dovecot failed..."
-#	exit 1
-#fi
-#make install
-#if [ $? -eq 1 ]; then
-#	echo "ERROR make install dovecot failed..."
-#	exit 1
-#fi
+cd /usr/local/src/dovecot
+wget http://dovecot.org/releases/2.2/dovecot-$dovecot_version.tar.gz
+# compile dovecot
+tar -xzvf dovecot-$dovecot_version.tar.gz
+cd dovecot-$dovecot_version
+./configure --prefix=/usr/local/dovecot/$dovecot_version --with-shadow --with-pam --with-ssl=openssl --sysconfdir=/etc
+make
+if [ $? -eq 1 ]; then
+	echo "ERROR make dovecot failed..."
+	exit 1
+fi
+make install
+if [ $? -eq 1 ]; then
+	echo "ERROR make install dovecot failed..."
+	exit 1
+fi
 
 # compile pigeon
 cd /usr/local/src/dovecot
+wget http://www.rename-it.nl/dovecot/2.2/dovecot-2.2-pigeonhole-$pig_version.tar.gz
 tar -xzvf dovecot-2.2-pigeonhole-$pig_version.tar.gz
 cd dovecot-2.2-pigeonhole-$pig_version
 ./configure --with-dovecot=/usr/local/dovecot/$dovecot_version/lib/dovecot
@@ -43,6 +45,11 @@ fi
 # relink dovecot
 cd /usr/local/dovecot/$dovecot_version
 ln -s /etc/dovecot etc
+./bin/doveconf -c /usr/local/dovecot/$dovecot_version/etc/dovecot.conf
+if [ $? -ne 0 ]; then
+  echo "Configuration issues. Don't restart dovecot"
+  exit 0
+fi
 
 cd /usr/local/dovecot
 /etc/init.d/dovecot stop
